services:
  artwork:
    image: endlezz/artwork:${ARTWORK_VERSION:-latest}
    pull_policy: always
    env_file:
      - .env
    networks:
      - artwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "artwork-files:/var/www/html/storage"
      - 'artwork-mysql:/var/lib/mysql'
      - 'artwork-redis:/data'
      - 'artwork-meilisearch:/meili_data_v2'
networks:
  artwork:
    driver: bridge
volumes:
  artwork-mysql:
    driver: local
  artwork-meilisearch:
    driver: local
  artwork-redis:
    driver: local
  artwork-files:
    driver: local
