version: '3'

networks:
    laravel:


services:
    app:
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - php
            - redis
            - mysql
            - mailhog
            - meilisearch
        networks:
            - laravel

    mysql:
        image: mariadb:latest
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: artwork_tools
            MYSQL_USER: root
            MYSQL_PASSWORD: RootRoot
            MYSQL_ROOT_PASSWORD: RootRoot
        networks:
            - laravel

    meilisearch:
        image: getmeili/meilisearch:latest
        volumes:
            - ./data.ms:/data.ms
        networks:
            - laravel
        ports:
            - "0.0.0.0:7700:7700"
        environment:
            - --master-key=masterKey
            - --http-addr 'localhost:7700'

    php:
        build:
            context: ./dockerfiles
            dockerfile: php.root.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    websockets:
        build:
            context: ./dockerfiles/websockets
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        expose:
            - "3341"
        depends_on:
            - app
        networks:
            - laravel

    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel

    composer:
        build:
            context: ./dockerfiles
            dockerfile: php.root.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - .:/var/www/html
        depends_on:
            - php
        entrypoint: [ 'composer', '--ignore-platform-reqs' ]
        networks:
            - laravel

    npm:
        image: node:current-alpine
        volumes:
            - .:/var/www/html
        ports:
            - "3000:3000"
            - "3001:3001"
            - "5173:5173"
        working_dir: /var/www/html
        entrypoint: [ 'npm' ]
        networks:
            - laravel

    artisan:
        build:
            context: ./dockerfiles
            dockerfile: php.root.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        entrypoint: [ 'php', '/var/www/html/artisan' ]
        networks:
            - laravel

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - laravel
