services:
  meilisearch:
    container_name: ddev-${DDEV_SITENAME}-meilisearch
    hostname: ${DDEV_SITENAME}-meilisearch
    image: getmeili/meilisearch:v1.9
    networks: [default, ddev_default]
    restart: "on-failure"
    expose:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY:-ddev}
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=7700:7700
      - HTTPS_EXPOSE=7701:7700
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - "meili_data:/meili_data"
      - ".:/mnt/ddev_config"
  web:
    links:
      - meilisearch:meilisearch
volumes:
  meili_data: