name: PHPStan

on:
  push:
    branches:
      - dev
      - main
      - staging
      - pipeline
    tags:
      - 'v*'
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: '0 0 * * *'
jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Composer Setup
        uses: php-actions/composer@v6
        with:
          php_version: 8.2
          php_extensions: gd zip bcmath pcntl

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: app/ artwork/
          php_version: 8.2
          php_extensions: gd zip bcmath pcntl
